apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sjrk-story-telling.fullname" . }}
  labels:
    {{- include "sjrk-story-telling.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
{{- end }}
  selector:
    matchLabels:
      {{- include "sjrk-story-telling.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sjrk-story-telling.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: COUCHDB_URL
              value: {{ .Values.databaseURL }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/sjrk.storyTelling.server.config.json5
              subPath: sjrk.storyTelling.server.config.json5
            - name: secrets-volume
              mountPath: /usr/src/app/secrets.json
              subPath: secrets.json
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "sjrk-story-telling.fullname" . }}-config
            items:
              - key: config
                path: sjrk.storyTelling.server.config.json5
        - name: secrets-volume
          secret:
            secretName: {{ include "sjrk-story-telling.fullname" . }}-secrets
            items:
              - key: secrets
                path: secrets.json
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
